"""Add receiving_bkash_number to Order

Revision ID: 0dddf5a3512f
Revises: 478225ce46e8
Create Date: 2025-11-12 20:43:31.345287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dddf5a3512f'
down_revision = '478225ce46e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiving_bkash_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('receiving_bkash_number')
    # ### end Alembic commands ###
