"""add delivery fee model and order delivery fields

Revision ID: 26f114395224
Revises: 37fdac6e2fcb
Create Date: 2025-11-08 04:37:11.492723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f114395224'
down_revision = '37fdac6e2fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_type')

    op.drop_table('delivery_fee')
    # ### end Alembic commands ###
