"""Add slug field to BlogPost model

Revision ID: 478225ce46e8
Revises: 4c6f67998785
Create Date: 2025-11-11 09:18:31.492510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478225ce46e8'
down_revision = '4c6f67998785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=250), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_post_slug'), ['slug'], unique=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_order_coupon_id', 'coupon', ['coupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_coupon_id', type_='foreignkey')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('coupon_id')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
