"""empty message

Revision ID: 4c6f67998785
Revises: 26f114395224
Create Date: 2025-11-08 05:10:07.132643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6f67998785'
down_revision = '26f114395224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_subscriber_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriber_email'))

    op.drop_table('newsletter_subscriber')
    # ### end Alembic commands ###
