"""Add is_banned and created_at to User

Revision ID: ee3fd688d25d
Revises: 0f9e410fc471
Create Date: 2025-11-07 20:42:04.160789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3fd688d25d'
down_revision = '0f9e410fc471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # SQLite cannot add a NOT NULL column without a server default for existing rows.
        # Provide a server_default of 0 (false) so the ALTER succeeds, then you can
        # remove the server_default in a follow-up migration if desired.
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
